name: Deploy serverless application on AWS

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install dependencies
        run: npm ci

      - name: Deploy to stage $STAGE
        run: npm run sls -- deploy --region $REGION --stage $STAGE
        env:
          REGION: us-east-1
          STAGE: ci-test
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run integration tests
        run: npm run integration-test

      - name: Remove from stage $STAGE
        run: npm run sls -- remove --region $REGION --stage $STAGE
        env:
          REGION: us-east-1
          STAGE: ci-test
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  deploy:
    needs: integration-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Install dependencies
        run: npm ci

      - name: Deploy to stage $STAGE
        run: npm run sls -- deploy --region $REGION --stage $STAGE
        env:
          REGION: us-east-1
          STAGE: staging
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
